#!/bin/sh 
#-----------------------------------------------------------------------
# Fuction: gen_local_properties.sh
# Version: 1.0
# Created: Tuyj
# Created date:2017/04/21
# Parameters:
#   $1 -- Output path
#-----------------------------------------------------------------------

if [ ! $# -eq 1 ]
then
    echo "Input error. Usage:"
    echo "  \$1  -- Output path. It looks like project root path"
    exit 1
fi 

OUT_LOCAL_PROPERTIES_FILE="$1/local.properties"

if [ -z "${SDK_HOME}" ] ;then
 echo !!!! \"SDK_HOME\" is not set. Use default value "/opt/soft/android/sdk"
 SDK_HOME=/opt/soft/android/sdk
fi

if [ -z "${NDK_HOME}" ] ;then
 echo !!!! \"NDK_HOME\" is not set. Use default value "/opt/android-ndk-r13b"
 NDK_HOME=/opt/android-ndk-r13b
fi

if [ -z "${NDK_TOOLCHAIN_HOME}" ] ;then
 echo !!!! \"NDK_TOOLCHAIN_HOME\" is not set. Use default value "/opt"
 NDK_TOOLCHAIN_HOME=/opt
fi

echo "## This file is automatically generated by module_libraries/scripts/gen_local_properties.sh." > ${OUT_LOCAL_PROPERTIES_FILE} 
echo "# Do not modify this file -- YOUR CHANGES WILL BE ERASED!" >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "#" >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "# This file must *NOT* be checked into Version Control Systems," >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "# as it contains information specific to your local configuration." >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "#" >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "# Location of the SDK. This is only used by Gradle." >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "# For customization when using a Version Control System, please read the" >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "# header note." >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "# `date`" >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "ndk.dir=${NDK_HOME}" >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "sdk.dir=${SDK_HOME}" >> ${OUT_LOCAL_PROPERTIES_FILE} 
echo "toolchains.dir=${NDK_TOOLCHAIN_HOME}" >> ${OUT_LOCAL_PROPERTIES_FILE} 

